### ISSUE TITLE
[FE] Set up navigation & initial pages

### ISSUE THREAD

**Issue by michelleykim** [ubctaekwondo/taekwon-app#2]
Set up navigation and pages
- You don't have to worry about the content of each pages for now. You can literally add `<p>[page name]</p>` in each page so we can see that the routing actually works
- To give you some idea, this is one way you can organize pages:  
app
│
├── auth                # Folder for authentication-related screens
│   ├── signIn.tsx      # Sign In screen
│   └── signUp.tsx      # Sign Up screen
│
├── landing             # Folder for the landing page and its tabs
│   ├── _layout.tsx     # Layout for the landing page with tabs
│   ├── today.tsx      # Today tab screen
│   ├── calendar.tsx    # Calendar tab screen
│   └── announcement.tsx # Announcement tab screen
│
├── admin               # Folder for admin-related pages
│   ├── _layout.tsx     # Layout for admin section
│   ├── manageSchedule.tsx  # Manage Schedule page
│   ├── manageSponsor.tsx  # Manage Sponsor page
│   ├── manageMembership.tsx  # Manage Membership page
│   └── manageAnnouncement.tsx # Manage Announcement page
│
├── _layout.tsx         # Main layout for the entire app
├── +html.tsx           # HTML configuration for web (if needed)
└── +not-found.tsx      # 404 not found screen

**Comment by jacoblum22** [comment]
Connected to commit https://github.com/ubctaekwondo/taekwon-app/commit/482cec6a8c56d68d0c0c117c2295ff78d2c83179
